### ISSUE TITLE
I am having some issues with hugo-profile

### ISSUE THREAD

**Issue by dombraccia** [gurusabarish/hugo-profile#11]
Hi @gurusabarish,

First of all, thank you for putting hugo-profile together, I really like the layout for my personal site. 

However, I am having trouble with a few things.

1. I am having trouble making a separate tab next to the "Blog" tab. I want to have a CV tab for my CV, but when I put a "CV" folder in content/ and then add a cv.md file to that folder, nothing shows up on the CV tab when I click it.
2. Another issue is that when I go to the blog page of my site, I can still see the tags for your example blogs showing markdown syntax. 

Here is what my site looks like now so you can see: dbraccia.com

Any help with this would be much appreciated.

**Comment by gurusabarish** [comment]
Hi @dombraccia, 

> Another issue is that when I go to the blog page of my site, I can still see the tags for your example blogs showing markdown syntax.

Now, it fixed. you can download and use the theme.

>I am having trouble making a separate tab next to the "Blog" tab. I want to have a CV tab for my CV, but when I put a "CV" folder in content/ and then add a cv.md file to that folder, nothing shows up on the CV tab when I click it.

I think, you named the file as cv.html
Did you try cv.md? If its not work, please post your config file details here.

Thank you for your issue. It made the theme better.

**Comment by dombraccia** [comment]
Hi @gurusabarish 

Thanks for the help. I tried making it a markdown file and adding it to the content folder and still gives me a 404 error when I go to it.

Here is my config file:

```
baseURL: "https://dbraccia.com/"
publishDir: "dombraccia.github.io"
languageCode: "en-us"
title: "Personal site for Domenick J. Braccia"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxx-x
disqusShortname:
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  favicon: "/images/me.jpg"
  #description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2021"

  # Navbar Menus
  customMenus:
    - name: "CV"
      Url: "/cv"
    - name: "Blog"
      Url: "/blog"

  # social
  name: "Domenick"
  github: "https://github.com/dombraccia"
  linkedin: ""
  twitter: "https://twitter.com/dombraccia"

  # About
  profile_image: "/images/me.jpg"
  descripe_l1_person: "I am a PhD candidate at the University of Maryland, studying bioinformatics and computational biology. My current research focus is on characterizing health relevant functions of the gut microbiome."
  descripe_l2_person: "Generally, I am interested in using computational tools to answer biological questions. I also enjoy creating algorithms to solve a particular problems in biological sequence analysis."
  useresume: false
  resume: ""

  # Things I do
  usedothings: false
  Things:
    - logo: fab fa-python
      title: Python
      description: I write programs using R

    - logo: fas fa-robot
      title: Machine learning
      description: I train robust models for various tasks.

    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web

  #Description for seo. If you want to show description in your listing or single page, let's make it true
  showdescription: false
```

**Comment by dombraccia** [comment]
Ok, it does actually seem to work once I put the CV.md in the right folder and configure the config file correctly.

But I still have a few issues. I think that I would like to use the "Resume" button that you include on the homepage, but I want to change it to name it "CV". 

Also, how do I get rid of the option for the "Tweet" button on each content post? It is certainly nice for blogs and such, but I may not want it there for everything that I have up

**Comment by dombraccia** [comment]
Also, is it possible to toggle (remove) the "Recent posts" section easily?

**Comment by gurusabarish** [comment]
Hi @dombraccia,

> Also, how do I get rid of the option for the "Tweet" button on each content post? It is certainly nice for blogs and such, but I    may not want it there for everything that I have up
Also, is it possible to toggle (remove) the "Recent posts" section easily?

I added option for remove tweet button and recent posts section.

> I also have a few other issues. I think that I would like to use the "Resume" button that you include on the homepage, but I want to change it to name it "CV".
I tried making it a markdown file and adding it to the content folder and still gives me a 404 error when I go to it.

I am working on it 

Sorry for the late response, Thank you

**Comment by dombraccia** [comment]
Thank you! I see that you have made a few changes, so I have pulled the latest version of the theme to my local.

However, I am not sure how to modify my config file or my content files to toggle the tweet button or recent post sections. Could you provide an example line that I would use in the config file to do this?

And I appreciate the help with the CV / resume thing. That is one of the things I am most interested in, so that would really help a lot.

**Comment by gurusabarish** [comment]
Now, I updated the code to rename the button. Below link help you to modify.
https://github.com/gurusabarish/hugo-profile/blob/master/exampleSite/config.yaml

> And I appreciate the help with the CV / resume thing. That is one of the things I am most interested in, so that would really help a lot.

Just create a folder named cv and create a index.md file. Index file should have the all content. It woks for me.

If you like this template, just give a star. It motivates me to do further projects. Thank you 😊

**Comment by dombraccia** [comment]
We are getting super close...

Everything works when I try it locally and checking with localhost:1313/. But when I build my site with `hugo` and then push those changes, I get a 404 error on both the red CV (resume) button at the bottom and on the CV menu item at the top. If you go to my site you can see what I mean: dbraccia.com.

Any idea why it would work locally and not when published?

**Comment by dombraccia** [comment]
here is what my config file looks like now for your reference:

```
baseURL: "https://dbraccia.com/"
publishDir: "dombraccia.github.io"
languageCode: "en-us"
title: "Personal site for Domenick J. Braccia"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxx-x
disqusShortname:
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  favicon: "/images/me.jpg"
  #description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2021"

  # Navbar Menus
  customMenus:
    - name: "CV"
      Url: "/cv"
    - name: "Blog"
      Url: "/blog"

  # social
  name: "Domenick"
  github: "https://github.com/dombraccia"
  linkedin: ""
  twitter: "https://twitter.com/dombraccia"

  # About
  profile_image: "/images/me.jpg"
  descripe_l1_person: "I am a PhD candidate at the University of Maryland, studying bioinformatics and computational biology. My current research focus is on characterizing health relevant functions of the gut microbiome." 
  descripe_l2_person: "Generally, I am interested in using computational tools to answer biological questions. I also enjoy creating algorithms to solve a particular problems in biological sequence analysis."
  useresume: true
  customname: "CV" 
  resumelink: "/cv"

  # Things I do
  usedothings: false
  Things:
    - logo: fab fa-python
      title: Python
      description: I write programs using R

    - logo: fas fa-robot
      title: Machine learning
      description: I train robust models for various tasks.

    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web

  #Description for seo. If you want to show description in your listing or single page, let's make it true
  showdescription: false
```
