### ISSUE TITLE
Is it possible to add additional menus in the top?

### ISSUE THREAD

**Issue by rajganeshp** [gurusabarish/hugo-profile#4]
Is it possible to add additional menus in the top? if you can, can you show an example?

**Comment by gurusabarish** [comment]
Yes, of course you can. 
In config file [here](https://github.com/gurusabarish/hugo-profile/blob/ecbb186f721ebdeb3ebcaed85507239c7a3f1f67/exampleSite/config.yaml#L19), add your menus as the below.
```yaml
customMenus:
  - name: "Blog"
    Url: "/blog"

  # Your menus
  - name: "your title"
    Url: "https://example.com"
```
