### ISSUE TITLE
Wierd issue?

### ISSUE THREAD

**Issue by rajganeshp** [gurusabarish/hugo-profile#6]
MY site was working fine. But suddenly no matter what I do, it's showing your website with your details. I deleted the examplesite, all contents, etc. All I see is my content. I even tried with incognito mode. I know it's sound very wierd, but i'm not sure where it's picking up your content. Any ideas?

**Comment by rajganeshp** [comment]
Okay, it's due to this line. I add my substack though. this line causes it to use your content. Any reasons why?
Params:
    #footer
    embed: <iframe src="https://connectthoughts.substack.com/embed" width="480" height="320" ></iframe>

**Comment by gurusabarish** [comment]
Could you send the website link?

**Comment by rajganeshp** [comment]
https://www.connectthoughts.com/

**Comment by gurusabarish** [comment]
Just now, I pushed some code. So, please use the latest to disable social icons.

I made a config file for you please make this as yours with some customization. **Change the google analytics and disqus, favicon, description, profile image, think i do content and so.**

```yaml
baseURL: "https://www.connectthoughts.com"
languageCode: "en-us"
title: "Connecting Thoughts"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxx-xx
disqusShortname: yourdisqusname
Paginate: 8

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: ""
  description: ""
  copyright: "2020"

  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "/blog"

  - name: "Course"
    Url: "/course"
    
  # social
  name: "Raj Pandurangan"
  github: "https://github.com/rajganeshp"
  linkedin: "https://linkedin.com/in/rajganeshp"
  twitter: "https://twitter.com/rajganeshp"
  instagram: ""

  # About
  profile_image: ""
  descripe_l1_person: "I’m a capable Presales architect who can act as the glue that links together mission critical security requirements. Articulate and effective communicator who has a history of developing products that push the limits of technology. Able to respond to the ever changing demands of clients by creating innovative high quality and defect-free security solutions that precisely meet their business needs. Strong management and methodical aptitude with an innate ability in decision-making, coordinating and synthesizing data."
  descripe_l2_person: ""
  job: "Cybersecurity Specialist "
  resume: "https://www.connectthoughts.com/about"

  # Things I do
  usedothings: true
  Things:
    - logo: fab fa-python
      title: title
      description: This is description

    - logo: fas fa-robot
      title:  title
      description: This is description 

    - logo: fab fa-html5
      title: title
      description: This is description
    
    - logo: fab fa-html5
      title: title
      description: This is description

  #blog ( Description for seo. If you want to show description in your blog post, let's make it true)
  showdescription: true

Author:
  name: ""
  website: ""

```
