### ISSUE TITLE
How to customize h2 title "Blogs"

### ISSUE THREAD

**Issue by artis3n** [gurusabarish/hugo-profile#81]
I am not seeing a way to customize the title that appears at https://hugo-profile.netlify.app/blogs/ . This looks to be generated from https://github.com/gurusabarish/hugo-profile/blob/master/layouts/_default/list.html#L12 where `Title` is set by front matter(?) or uses the site's main title.

How am I supposed to set this variable appropriately as an end user?

For example, for the navbar I have configured the following in my `config.yaml`:

```yaml
Menus:
  main:
    - identifier: blog
      name: Articles
      title: Blog posts
      url: /blog
      weight: 1
```

I would like the title of the `/blog` URL to be `Articles`, not `Blogs`. Nowhere in my config does "blogs" exist, yet it must be picked up from somewhere deeper in the theme to generate in this `.Title` field.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/6969296/205422358-22c1fa99-cd47-4527-9814-1c1fbf19b6e6.png">
