### ISSUE TITLE
Relative URL in sections

### ISSUE THREAD

**Issue by torvenkat** [gurusabarish/hugo-profile#98]
Will it be possible to make relative URL (linking to a page or post within the site) in various sections (Education, Projects, etc)? 

I am not sure, if this already possible.  If so, I would like to know how to include a relative URL.

**Comment by gurusabarish** [comment]
Can explain your need with more details ?

**Comment by torvenkat** [comment]
In a section (say Education), if I want to refer to an internal page, how do I link?   We now have 
```
     featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
```
Instead I want the URL to refer an internal page or blog post.

**Comment by pantera-rosa** [comment]
hey @torvenkat, if you want to link to an internal page, just write the page in where you'd write the URL. for example, let's say I want my featured link to go to my `blogs` page, and let's say my personal website is located at `MyPersonalWebsite.com`, my config should look like this:

```     
     featuredLink:
            enable: true
            name: "My Personal Blog"
            url: "blog"
```

and clicking on that link would redirect me to `MyPersonalWebsite.com/blog`. 

If I wanted to just redirect to a different section of my home page, let's say I wanted to go to the `Contact` section, I can just put in `#contact` in that field and I'd be redirected to `MyPersonalWebsite.com/#contact`. You can even put in your own URL into that field and it will still route you where you want to go (for example, you could put in `url: "https://MyPersonalWebsite.com/#contact"` and that link should still successfully redirect you to that page). Hope this answers your question!
